name: Versioning on Merge
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current version
        id: version
        run: |
          # Если версия хранится в файле (например, version.txt)
          if [ -f "version.txt" ]; then
            CURRENT_VERSION=$(cat version.txt)
          else
            CURRENT_VERSION="0.1.0"  # Дефолтная версия
          fi
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Bump version (Patch)
        id: bump
        uses: phips28/gh-action-bump-version@v10
        with:
          tag-prefix: "v"
          skip-tag: false
          skip-commit: false
          default-bump: "patch"  # Увеличивает третью цифру (0.1.0 → 0.1.1)
          # Можно заменить на minor/major при необходимости

      - name: Push new version tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push --tags