---
  on:
    push:
      branches: [main]
  
  name: Generate SemVer Version
  
  permissions:
    contents: read
  
  concurrency:
    group: "${{ github.ref }}-${{ github.workflow }}"
    cancel-in-progress: true
  
  jobs:
    versioning:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - name: calculate version
          id: calculate-version
          uses: bitshifted/git-auto-semver@v1
          with:
            main_branch: main
            create_tag: true
        - name: Use version
          run: 'echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"'