name: Auto Versioning

on:
  push:
    branches: [main]

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: |
          # Получаем последний тег или используем 0.1.0 по умолчанию
          if git describe --tags --abbrev=0 2>/dev/null; then
            TAG=$(git describe --tags --abbrev=0)
            echo "current_version=${TAG#v}" >> $GITHUB_OUTPUT
          else
            echo "current_version=0.1.0" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        id: bump_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.current_version }}
          IFS='.' read -ra VERSION <<< "$CURRENT_VERSION"
          NEW_VERSION="${VERSION[0]}.${VERSION[1]}.$((VERSION[2] + 1))"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "Bumping version from ${CURRENT_VERSION} to ${NEW_VERSION}"

      - name: Create new tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a "v${{ steps.bump_version.outputs.new_version }}" \
              -m "Version ${{ steps.bump_version.outputs.new_version }}"
          git push origin "v${{ steps.bump_version.outputs.new_version }}"